2023-01-12 16:26:58,423 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.author_en_us_id'), <traceback object at 0x000002BF27B49200>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.author_en_us_id
2023-01-12 16:26:58,427 ERROR  "GET / HTTP/1.1" 500 223902 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-12 16:27:12,614 ERROR  Internal Server Error: /news/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.author_en_us_id'), <traceback object at 0x000002BF2789D080>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.author_en_us_id
2023-01-12 16:27:12,616 ERROR  "GET /news/ HTTP/1.1" 500 224104 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-12 16:30:18,380 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.author_en_us_id'), <traceback object at 0x000002BF279F1B00>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.author_en_us_id
2023-01-12 16:30:18,382 ERROR  "GET / HTTP/1.1" 500 223902 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-12 16:33:24,368 ERROR  Internal Server Error: /3 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.categoryType_en_us'), <traceback object at 0x000002636EF09180>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.categoryType_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\detail.py", line 53, in get_object
    obj = queryset.get()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.categoryType_en_us
2023-01-12 16:33:24,372 ERROR  "GET /3 HTTP/1.1" 500 158646 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-12 16:33:51,267 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.categoryType_en_us'), <traceback object at 0x000002636EDA1100>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.categoryType_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.categoryType_en_us
2023-01-12 16:33:51,271 ERROR  "GET / HTTP/1.1" 500 222021 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-12 16:34:05,734 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.dataCreation_en_us'), <traceback object at 0x00000203C8735300>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.dataCreation_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.dataCreation_en_us
2023-01-12 16:34:05,739 ERROR  "GET / HTTP/1.1" 500 220950 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-12 16:34:19,735 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.dataCreation_en_us'), <traceback object at 0x00000203C8A712C0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.dataCreation_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.dataCreation_en_us
2023-01-12 16:34:19,737 ERROR  "GET / HTTP/1.1" 500 221087 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-12 16:54:51,367 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_category.name_en_us'), <traceback object at 0x000001FD03AE3400>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_category.name_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_category.name_en_us
2023-01-12 16:54:51,373 ERROR  "GET / HTTP/1.1" 500 239936 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-13 11:37:56,009 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.dataCreation_en_us'), <traceback object at 0x000002BD1B3A62C0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.dataCreation_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.dataCreation_en_us
2023-01-13 11:37:56,013 ERROR  "GET / HTTP/1.1" 500 220950 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-13 11:38:57,538 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.categoryType_en_us'), <traceback object at 0x00000249900901C0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.categoryType_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.categoryType_en_us
2023-01-13 11:38:57,542 ERROR  "GET / HTTP/1.1" 500 222021 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-13 20:54:57,598 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.dataCreation_en_us'), <traceback object at 0x000002404A797E80>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.dataCreation_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.dataCreation_en_us
2023-01-13 20:54:57,603 ERROR  "GET / HTTP/1.1" 500 220950 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-13 20:55:44,353 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x0000017B264642C0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaultfilters.py", line 606, in length
    return len(value)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_post.title_en_us
2023-01-13 20:55:44,361 ERROR  "GET / HTTP/1.1" 500 219648 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-16 20:18:04,929 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_category.name_en_us'), <traceback object at 0x000001B1D6D3B980>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_category.name_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_category.name_en_us
2023-01-16 20:18:04,937 ERROR  "GET / HTTP/1.1" 500 332224 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-18 19:53:02,319 ERROR  Internal Server Error: /news/search/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 39: 'endcache', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001E43BA16CC0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endcache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 39: 'endcache', expected 'endblock'. Did you forget to register or load this tag?
2023-01-18 19:53:02,322 ERROR  "GET /news/search/ HTTP/1.1" 500 218145 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-18 19:54:07,740 ERROR  Internal Server Error: /news/search/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 39: 'endcache', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x0000022533423980>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endcache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 39: 'endcache', expected 'endblock'. Did you forget to register or load this tag?
2023-01-18 19:54:07,744 ERROR  "GET /news/search/ HTTP/1.1" 500 219519 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-19 20:03:24,882 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'RecursionError'>, RecursionError('maximum recursion depth exceeded'), <traceback object at 0x00000150B8AA9E80>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\NewsPaper\news\views.py", line 56, in get_queryset
    self.filterset = PostFilter(self.request.GET, queryset=self.get_queryset())
  File "C:\Users\work\PycharmProjects\project_NewsPortal\NewsPaper\news\views.py", line 56, in get_queryset
    self.filterset = PostFilter(self.request.GET, queryset=self.get_queryset())
  File "C:\Users\work\PycharmProjects\project_NewsPortal\NewsPaper\news\views.py", line 56, in get_queryset
    self.filterset = PostFilter(self.request.GET, queryset=self.get_queryset())
  [Previous line repeated 935 more times]
  File "C:\Users\work\PycharmProjects\project_NewsPortal\NewsPaper\news\views.py", line 55, in get_queryset
    queryset = super().get_queryset()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\views\generic\list.py", line 34, in get_queryset
    queryset = self.model._default_manager.all()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\manager.py", line 164, in all
    return self.get_queryset()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\modeltranslation\manager.py", line 552, in get_queryset
    qs = super(MultilingualManager, self).get_queryset()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\modeltranslation\manager.py", line 527, in get_queryset
    qs = super(MultilingualQuerysetManager, self).get_queryset()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\manager.py", line 155, in get_queryset
    return self._queryset_class(model=self.model, using=self._db, hints=self._hints)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 294, in __init__
    self._query = query or sql.Query(self.model)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\db\models\sql\query.py", line 249, in __init__
    self.where = WhereNode()
RecursionError: maximum recursion depth exceeded
2023-01-19 20:03:24,894 ERROR  "GET / HTTP/1.1" 500 5508945 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-20 09:16:35,373 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x0000022B452DE380>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2023-01-20 09:16:35,378 ERROR  "GET / HTTP/1.1" 500 270184 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-20 09:44:13,954 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x000002390387BAC0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2023-01-20 09:44:13,959 ERROR  "GET / HTTP/1.1" 500 270184 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-20 09:55:17,497 ERROR  Internal Server Error: / C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name."), <traceback object at 0x000001B829CE8E00>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_timezone' not found. 'set_timezone' is not a valid view function or pattern name.
2023-01-20 09:55:17,504 ERROR  "GET / HTTP/1.1" 500 232195 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2023-01-23 16:56:32,084 ERROR  Internal Server Error: /swagger-ui/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('swagger-ui.html'), <traceback object at 0x000001FF7428C2C0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: swagger-ui.html
2023-01-23 16:56:32,085 ERROR  "GET /swagger-ui/ HTTP/1.1" 500 85478 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2025-07-03 10:51:05,338 ERROR  Internal Server Error: /subscriptions/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('subscriptions.html, news/subscription_list.html'), <traceback object at 0x000001DFC4C50E00>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: subscriptions.html, news/subscription_list.html
2025-07-03 10:51:05,338 ERROR  "GET /subscriptions/ HTTP/1.1" 500 93804 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2025-07-03 11:25:18,255 ERROR  Internal Server Error: /subscriptions/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('subscriptions.html, news/subscription_list.html'), <traceback object at 0x000001DF3139F340>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: subscriptions.html, news/subscription_list.html
2025-07-03 11:25:18,255 ERROR  "GET /subscriptions/ HTTP/1.1" 500 93804 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2025-07-03 11:28:18,366 ERROR  Internal Server Error: /subscriptions/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('subscriptions.html, news/subscription_list.html'), <traceback object at 0x0000015293F7C580>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: subscriptions.html, news/subscription_list.html
2025-07-03 11:28:18,366 ERROR  "GET /subscriptions/ HTTP/1.1" 500 93804 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2025-07-03 11:38:30,160 ERROR  Internal Server Error: /subscriptions/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news/subscriptions.html, news/subscription_list.html'), <traceback object at 0x0000015CADB142C0>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/subscriptions.html, news/subscription_list.html
2025-07-03 11:38:30,160 ERROR  "GET /subscriptions/ HTTP/1.1" 500 94053 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2025-07-03 11:39:39,527 ERROR  Internal Server Error: /subscriptions/ C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('subscriptions.html, news/subscription_list.html'), <traceback object at 0x00000279270BC980>)
Traceback (most recent call last):
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: subscriptions.html, news/subscription_list.html
2025-07-03 11:39:39,527 ERROR  "GET /subscriptions/ HTTP/1.1" 500 94105 C:\Users\work\PycharmProjects\project_NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
